# Generated by Django 5.2.4 on 2025-07-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostic',
            name='type_pari',
            field=models.CharField(choices=[('1N2', '1N2 (Résultat du match)'), ('OVER_UNDER', 'Over/Under (Total de points/buts)'), ('HANDICAP', 'Handicap'), ('BUTEUR', 'Buteur/Marqueur'), ('DOUBLE_CHANCE', 'Double Chance'), ('MI_TEMPS_FIN_MATCH', 'Mi-temps/Fin de match'), ('SCORE_EXACT', 'Score Exact'), ('AUTRE', 'Autre')], default='1N2', max_length=50, verbose_name='Type de pari'),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='cote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cote'),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='mise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mise (€)'),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='prediction_details',
            field=models.TextField(verbose_name='Analyse et détails de la prédiction'),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='prediction_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prédiction de score (optionnel)'),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='resultat',
            field=models.CharField(choices=[('EN_COURS', 'À venir'), ('GAGNANT', 'Gagnant'), ('PERDANT', 'Perdant'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=50, verbose_name='Statut du pronostic'),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='score_final_domicile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score final domicile'),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='score_final_exterieur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score final extérieur'),
        ),
    ]
