# Generated by Django 5.2.4 on 2025-07-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0002_pronostic_type_pari_alter_pronostic_cote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostic',
            name='thesportsdb_event_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="ID d'événement TheSportsDB"),
        ),
    ]
