# Generated by Django 5.2.4 on 2025-08-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0003_pronostic_thesportsdb_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronostic',
            name='thesportsdb_event_id',
        ),
    ]
