# Generated by Django 5.2.4 on 2025-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0004_remove_pronostic_thesportsdb_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostic',
            name='api_event_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID d'événement API-Sports"),
        ),
    ]
