# Generated by Django 5.2.4 on 2025-08-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0005_pronostic_api_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmakerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Bookmaker')),
                ('bonus_description', models.CharField(max_length=255, verbose_name='Description du Bonus')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code Promo')),
                ('registration_link', models.URLField(verbose_name="Lien d'inscription")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bookmaker_logos/', verbose_name='Logo')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offre de Bookmaker',
                'verbose_name_plural': 'Offres de Bookmakers',
                'ordering': ['order', 'name'],
            },
        ),
    ]
