# Generated by Django 5.2.4 on 2025-08-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0006_bookmakeroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostic',
            name='bookmaker_recommande',
            field=models.ForeignKey(blank=True, help_text='Bookmaker où ce pronostic pourrait être placé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronostics_lies', to='profoot.bookmakeroffer', verbose_name='Bookmaker Recommandé'),
        ),
        migrations.AddField(
            model_name='pronostic',
            name='lien_pari',
            field=models.URLField(blank=True, help_text='URL directe vers le match ou le pari sur le site du bookmaker.', max_length=500, null=True, verbose_name='Lien direct vers le pari'),
        ),
    ]
