# Generated by Django 5.2.4 on 2025-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0007_pronostic_bookmaker_recommande_pronostic_lien_pari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_event_id', models.IntegerField(db_index=True, unique=True, verbose_name="ID d'événement API-Sports")),
                ('date_match', models.DateTimeField(verbose_name='Date et Heure du Match')),
                ('ligue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ligue')),
                ('equipe_domicile', models.CharField(max_length=255, verbose_name='Équipe à domicile')),
                ('equipe_exterieur', models.CharField(max_length=255, verbose_name="Équipe à l'extérieur")),
                ('status_short', models.CharField(blank=True, max_length=10, null=True, verbose_name='Statut court API')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['date_match'],
            },
        ),
    ]
