# Generated by Django 5.2.4 on 2025-08-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0008_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
