# Generated by Django 5.2.4 on 2025-08-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profoot', '0009_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_event_id', models.BigIntegerField(db_index=True, unique=True, verbose_name="ID d'événement Sportmonks")),
                ('discipline', models.CharField(default='FOOTBALL', max_length=50, verbose_name='Discipline')),
                ('equipe_domicile', models.CharField(max_length=100, verbose_name='Équipe Domicile')),
                ('equipe_exterieur', models.CharField(max_length=100, verbose_name='Équipe Extérieure')),
                ('date_match', models.DateTimeField(verbose_name='Date et Heure du Match')),
                ('ligue', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ligue')),
                ('stade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stade')),
                ('score_final_domicile', models.IntegerField(blank=True, null=True, verbose_name='Score Final Domicile')),
                ('score_final_exterieur', models.IntegerField(blank=True, null=True, verbose_name='Score Final Extérieur')),
                ('status_api', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut API du Match')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match Sportif',
                'verbose_name_plural': 'Matchs Sportifs',
                'ordering': ['date_match'],
            },
        ),
        migrations.RemoveField(
            model_name='pronostic',
            name='api_event_id',
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='date_match',
            field=models.DateTimeField(blank=True, help_text='Date et heure du match (du match associé)', null=True),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='equipe_domicile',
            field=models.CharField(blank=True, help_text="Nom de l'équipe domicile (du match associé)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='equipe_exterieur',
            field=models.CharField(blank=True, help_text="Nom de l'équipe extérieure (du match associé)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='heure_match',
            field=models.TimeField(blank=True, help_text='Heure du match (du match associé)', null=True),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='ligue',
            field=models.CharField(blank=True, help_text='Ligue du match (du match associé)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pronostic',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pronostics', to='profoot.match', verbose_name='Match Associé'),
            preserve_default=False,
        ),
    ]
